### ISSUE TITLE
fop and site generation issues (docbook?)

### ISSUE THREAD

**Issue by jasonm** [schacon/git-scribe#23]
I get "I/O error : Attempt to load network entity" and similar issues on PDF generation: https://gist.github.com/08630344068dba46b610

I have fop 1.0 on OSX installed by homebrew:

```
[master][~/dev/backbone-js-on-rails] brew info fop
fop 1.0
http://xmlgraphics.apache.org/fop/index.html
/usr/local/Cellar/fop/1.0 (3753 files, 94M)
http://github.com/mxcl/homebrew/commits/master/Library/Formula/fop.rb
```

The 'site' generation also has an issue, included in the gist above.

I noticed the issue is similar to http://fvue.nl/wiki/Docbook_xsl:import:_unable_to_load_docbook.xsl so I installed docbook via `brew install docbook` in hope, but this didn't affect the issue.

Thoughts?

**Comment by JonathanTron** [comment]
it worked for me after installing docbook via homebrew and running the `sudo docbook-register` command.

**Comment by jasonm** [comment]
Thanks Jonathon - not sure how I missed that in the "Caveats" output section of homebrew.  This fixed it!
