### ISSUE TITLE
The site (http://gitscribe.com/) is not responding

### ISSUE THREAD

**Issue by sfermigier** [schacon/git-scribe#32]
Where can we find the documentation then ?

**Comment by klaut** [comment]
same here. the site is not responding.

**Comment by sebix** [comment]
This is definitely no issue, which belongs to Github!

**Comment by xee5ch** [comment]
Any update? Having the same issue.

**Comment by cappert** [comment]
Hi, I found the docs in the schacon/gs-manual repo : 

https://github.com/schacon/gs-manual/blob/master/book/book.asc

**Comment by schacon** [comment]
Yup, the site was lost.  It wasn't being used and I forgot to renew.
