### ISSUE TITLE
asciidoc: WARNING: missing theme: scribe

### ISSUE THREAD

**Issue by matthewmccullough** [schacon/git-scribe#37]
## Error

```
$ git-scribe gen html
GENERATING HTML
asciidoc: WARNING: missing theme: scribe
```
## Description

clone the code:
`git clone https://github.com/schacon/git-scribe`

see file:

```
lib/git-scribe/generate.rb
100:      cmd = "asciidoc -a stylesdir=#{styledir} -a theme=scribe #{BOOK_FILE}"
```
## Problem

I don't know what stylesdir is pointing to, but it isn't https://github.com/schacon/git-scribe/tree/master/stylesheets like it should be.
## Hack Fix

Copy this:

https://github.com/schacon/git-scribe/blob/master/stylesheets/scribe.css

Into a folder called `scribe`

That lives where your existing asciidoc themes live. For me that is:

/usr/local/Cellar/asciidoc/8.6.6/etc/asciidoc/themes

The existing themes are `volnitsky` or `flask` via the brew install of asciidoc.
## References

Plugins for asciidoc are described here and this is how I listed the ones I had installed:

http://www.methods.co.nz/asciidoc/userguide.html#X101

I could have configured this via a asciidoc.conf file and set it to use the existing themes or the one installed with git-scribe with a more explicit path (the relative path is not working)

http://www.methods.co.nz/asciidoc/userguide.html#X27

Themes are described here:

http://www.methods.co.nz/asciidoc/userguide.html#X99

**Comment by brettgoulder** [comment]
So I spent the morning up to my eyeballs in asciidoc docs and my opinion is to skip the theme plugin all together.  The theme plugin will look three places for the theme, 1) inside the asciidoc executable folder 2) inside your Asciidoc configuration folder as you described in your hack 3) inside the $HOME/.asciidoc folder if you create one. 

The better alternative is to use the option -a stylesheet="/absolute_path_to_your_css_file/*.css/".  This approach works well and will embed the stylesheet correctly in the html.  Will be submitting a pull request shortly.
