### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jessebikman** [schacon/git-scribe#47]
This link is dead, you might want to remove it: 
http://gitscribe.com/schacon/gs-manual/

**Comment by topfunky** [comment]
The entire http://gitscribe.com/ domain appears to be a placeholder site.

**Comment by matthewmccullough** [comment]
I think it unfortunately fell out of @schacon's hands.  Can you confirm @schacon?  If so, we should just purge all links to it perhaps.

**Comment by schacon** [comment]
Yuuuuuuuuuup.  Killed with :fire:
