### ISSUE TITLE
Unable to initialize, command not found

### ISSUE THREAD

**Issue by chrisfinazzo** [schacon/git-scribe#54]
I want to try out git-scribe but `git scribe init` returns `'scribe' is not a git command. See 'git --help'` and points to the Help files which (of course) know nothing about scribe. In addition, I've had limited success trying to diagnose what's going on as `git scribe check` returns the same `Not found` result. I am running this inside of a directory called `Book` which I am passing to the init command.

Any ideas?

**Comment by coldmug** [comment]
It seems that your installation might have been wrong. Did you follow the install instructions using gem?
